#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page
# Define the redirection URL
REDIRECT_URL="https://docs.nginx.com/nginx/admin-guide/web-server/"

# Replace the location block for /redirect_me with a redirection
sudo sed -i "s|^\s*location /redirect_me {.*|    location /redirect_me { return 301 $REDIRECT_URL; }|g" /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo systemctl restart nginx

