#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page

REDIRECT_URL="https://docs.nginx.com/nginx/admin-guide/web-server/"

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'

# Insert the redirect configuration using sed
sudo sed -i '/server_name _;/a \
    location /redirect_me {\
        return 301 '"$REDIRECT_URL"';\
    }' /etc/nginx/sites-available/default

sudo service nginx restart
