#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'

# Create the custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Insert the custom 404 error page configuration using sed
sudo sed -i '/server_name _;/a \
    error_page 404 /404.html;\
    location = /404.html {\
        internal;\
    }' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx restart
