#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 )

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/A-asava permanent;"
sudo sed -i "s/server_name _;/$string/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string/" /etc/nginx/sites-enabled/default

sudo sed -i "server_name _/a add_header X-Served-By $HOSTNAME;"  /etc/nginx/sites-enabled/default

sudo nginx -t

# Restart nginx after implementing changes
sudo service nginx restart
