#!/usr/bin/env bash
# script that generates a MySQL dump and creates a compressed archive out of it.

sudo mysqldump --all-databases -u root --password="$1" > backup.sql
day=$(date + "%d")
month=$(date + "%m")
year=$(date + "%Y")
file="$day-$month-$year.tar.gz"
tar -czvf "$file" backup.sql
