#!/usr/bin/env bash
# blocks all incoming traffic, except TCP ports: 22, 443, 80

sudo apt-get update
sudo apt-get install ufw
sudo ufw reset
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw enable
sudo ufw status
