#!/usr/bin/env bash
# Fixed container, Nginx is running as the nginx user.
sudo apt-get update
sudo apt-get install -y nginx
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u  nginx service nginx restart
