#!/usr/bin/env bash
# Fixed container, Nginx is running as the nginx user.
apt-get install -y nginx
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server/listen 8080 default_server/' /etc/nginx/sites-available/default
service nginx stop
service nginx start
