#!/usr/bin/env bash
# Fixed container, Nginx is running as the nginx user.
apt-get update
apt-get install -y nginx
sed -i "s/#user www-data;/user nginx;/" /etc/nginx/nginx.conf
sed -i "s/listen 80;/listen 8080;/" /etc/nginx/sites-available/default
pkill apache2
service nginx stop
service nginx start
